# Generated by Django 4.2.1 on 2023-09-01 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageAdd',
        ),
    ]
